"""Canonical Alert Contract for ThermalIntel V2.

Represents operational hazard notifications generated by rule evaluation
or intelligence anomalies, with deduplication and state tracking.
"""

from typing import Optional, Dict, Any, List
from pydantic import BaseModel, Field
from .common import AlertSeverity, AlertState, now_utc_iso


class AlertV2(BaseModel):
    """Canonical operational alert entity.
    
    Supports state transitions ('active' -> 'acknowledged' -> 'resolved'),
    deterministic deduplication via 'dedupe_key', and direct linkage
    to both Incidents and specific Observations.
    """
    alert_id: str = Field(..., description="Unique alert identifier (e.g. 'ALT-20261001-0001')")
    incident_id: Optional[str] = Field(None, description="Associated Incident identifier if correlated")
    observation_id: Optional[str] = Field(None, description="Specific trigger Observation identifier if applicable")
    rule_id: str = Field(..., description="Deterministic trigger rule identifier (e.g. 'RULE_EXTREME_FRP_PROXIMITY')")
    dedupe_key: str = Field(
        ...,
        description="Deterministic signature (e.g. 'INC-001:CRITICAL:EXTREME_FRP') preventing notification flooding"
    )
    priority: AlertSeverity = Field(..., description="Alert urgency level: info, warning, critical")
    state: AlertState = Field(default=AlertState.ACTIVE, description="Lifecycle status: active, acknowledged, resolved, suppressed")
    title: str = Field(..., description="Concise human-readable alert title")
    message: str = Field(..., description="Detailed situation report and context")
    evidence: Dict[str, Any] = Field(
        default_factory=dict,
        description="Structured forensic evidence supporting the alert (e.g. measured FRP, proximity meters, wind speed)"
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Operational responder tags, action recommendations, and dispatch routing"
    )
    
    # Lifecycle timestamps (Explicit UTC)
    created_at_utc: str = Field(default_factory=now_utc_iso, description="ISO 8601 UTC timestamp when alert was triggered")
    acknowledged_at_utc: Optional[str] = Field(None, description="ISO 8601 UTC timestamp when operator acknowledged the alert")
    resolved_at_utc: Optional[str] = Field(None, description="ISO 8601 UTC timestamp when condition was mitigated or closed")
