import {
  HealthResponse,
  Hotspot,
  IncidentDetail,
  SummaryResponse,
  AlertsResponse,
  SourcesResponse,
  Alert,
} from '../types/api';

export const mockHealth: HealthResponse = {
  status: 'ok',
  version: '0.1.0',
  data_mode: 'demo',
  timestamp: new Date().toISOString(),
  services: {
    database: 'connected (SQLite Fallback)',
    firms_api: 'ready (NASA VIIRS NRT Feed)',
    intelligence_engine: 'online (RandomForest + Anomaly Sigma v1.0)',
    weather_enrichment: 'online (Open-Meteo Synoptic API)',
    geospatial_enrichment: 'online (OpenStreetMap Overpass Engine)',
  },
};

export const mockHotspots: Hotspot[] = [
  {
    id: 'VIIRS-SNPP-20261001-001',
    latitude: 38.7421,
    longitude: -122.8105,
    brightness: 352.4,
    scan: 0.38,
    track: 0.36,
    acq_date: '2026-10-01',
    acq_time: '0845',
    satellite: 'Suomi-NPP',
    instrument: 'VIIRS',
    confidence: 'high',
    version: '2.0NRT',
    bright_t31: 298.4,
    frp: 142.8,
    daynight: 'N',
    source_type: 'wildfire',
    risk_score: 92.5,
    risk_level: 'critical',
    is_anomaly: true,
    cluster_id: 'CL-SONOMA-01',
    cluster_size: 5,
    nearest_place: 'Geysers Basin, Sonoma County, CA',
    last_updated: '2026-10-01T08:50:00Z',
  },
  {
    id: 'VIIRS-SNPP-20261001-002',
    latitude: 38.7468,
    longitude: -122.8052,
    brightness: 346.1,
    scan: 0.38,
    track: 0.36,
    acq_date: '2026-10-01',
    acq_time: '0845',
    satellite: 'Suomi-NPP',
    instrument: 'VIIRS',
    confidence: 'high',
    version: '2.0NRT',
    bright_t31: 296.2,
    frp: 118.2,
    daynight: 'N',
    source_type: 'wildfire',
    risk_score: 89.0,
    risk_level: 'critical',
    is_anomaly: true,
    cluster_id: 'CL-SONOMA-01',
    cluster_size: 5,
    nearest_place: 'Geysers Ridge, Sonoma County, CA',
    last_updated: '2026-10-01T08:50:00Z',
  },
  {
    id: 'VIIRS-NOAA20-20261001-003',
    latitude: 38.7392,
    longitude: -122.8164,
    brightness: 339.8,
    scan: 0.37,
    track: 0.35,
    acq_date: '2026-10-01',
    acq_time: '0912',
    satellite: 'NOAA-20',
    instrument: 'VIIRS',
    confidence: 'high',
    version: '2.0NRT',
    bright_t31: 294.7,
    frp: 86.4,
    daynight: 'N',
    source_type: 'wildfire',
    risk_score: 84.0,
    risk_level: 'critical',
    is_anomaly: true,
    cluster_id: 'CL-SONOMA-01',
    cluster_size: 5,
    nearest_place: 'Cobb Mountain Foothills, CA',
    last_updated: '2026-10-01T09:20:00Z',
  },
  {
    id: 'VIIRS-SNPP-20261001-004',
    latitude: 29.7154,
    longitude: -95.1248,
    brightness: 328.6,
    scan: 0.40,
    track: 0.38,
    acq_date: '2026-10-01',
    acq_time: '0730',
    satellite: 'Suomi-NPP',
    instrument: 'VIIRS',
    confidence: 'nominal',
    version: '2.0NRT',
    bright_t31: 293.1,
    frp: 24.3,
    daynight: 'N',
    source_type: 'industrial',
    risk_score: 26.5,
    risk_level: 'medium',
    is_anomaly: false,
    cluster_id: 'CL-HOU-IND',
    cluster_size: 1,
    nearest_place: 'Houston Ship Channel Refining Complex, TX',
    last_updated: '2026-10-01T07:45:00Z',
  },
  {
    id: 'VIIRS-NOAA20-20261001-005',
    latitude: 36.8122,
    longitude: -119.8214,
    brightness: 321.4,
    scan: 0.39,
    track: 0.37,
    acq_date: '2026-10-01',
    acq_time: '0915',
    satellite: 'NOAA-20',
    instrument: 'VIIRS',
    confidence: 'nominal',
    version: '2.0NRT',
    bright_t31: 292.0,
    frp: 31.8,
    daynight: 'N',
    source_type: 'agricultural',
    risk_score: 38.0,
    risk_level: 'medium',
    is_anomaly: false,
    cluster_id: null,
    cluster_size: 1,
    nearest_place: 'Central Valley Agricultural Sector, Fresno County, CA',
    last_updated: '2026-10-01T09:25:00Z',
  },
  {
    id: 'VIIRS-SNPP-20261001-006',
    latitude: 34.1852,
    longitude: -118.1528,
    brightness: 341.2,
    scan: 0.38,
    track: 0.36,
    acq_date: '2026-10-01',
    acq_time: '0848',
    satellite: 'Suomi-NPP',
    instrument: 'VIIRS',
    confidence: 'high',
    version: '2.0NRT',
    bright_t31: 295.3,
    frp: 76.5,
    daynight: 'N',
    source_type: 'wildfire',
    risk_score: 79.2,
    risk_level: 'critical',
    is_anomaly: true,
    cluster_id: 'CL-ANGELES-01',
    cluster_size: 2,
    nearest_place: 'Angeles National Forest Canyon, CA',
    last_updated: '2026-10-01T08:55:00Z',
  },
  {
    id: 'VIIRS-SNPP-20261001-007',
    latitude: 34.1904,
    longitude: -118.1481,
    brightness: 334.7,
    scan: 0.38,
    track: 0.36,
    acq_date: '2026-10-01',
    acq_time: '0848',
    satellite: 'Suomi-NPP',
    instrument: 'VIIRS',
    confidence: 'nominal',
    version: '2.0NRT',
    bright_t31: 294.0,
    frp: 54.1,
    daynight: 'N',
    source_type: 'wildfire',
    risk_score: 71.0,
    risk_level: 'high',
    is_anomaly: false,
    cluster_id: 'CL-ANGELES-01',
    cluster_size: 2,
    nearest_place: 'San Gabriel Ridge Trail, CA',
    last_updated: '2026-10-01T08:55:00Z',
  },
  {
    id: 'VIIRS-NOAA20-20261001-008',
    latitude: 44.3821,
    longitude: -121.7241,
    brightness: 329.5,
    scan: 0.41,
    track: 0.38,
    acq_date: '2026-10-01',
    acq_time: '0910',
    satellite: 'NOAA-20',
    instrument: 'VIIRS',
    confidence: 'nominal',
    version: '2.0NRT',
    bright_t31: 290.8,
    frp: 44.0,
    daynight: 'N',
    source_type: 'prescribed_burn',
    risk_score: 35.0,
    risk_level: 'medium',
    is_anomaly: false,
    cluster_id: null,
    cluster_size: 1,
    nearest_place: 'Deschutes National Forest Managed Unit, OR',
    last_updated: '2026-10-01T09:18:00Z',
  },
  {
    id: 'VIIRS-SNPP-20261001-009',
    latitude: 47.6085,
    longitude: -122.3361,
    brightness: 318.2,
    scan: 0.37,
    track: 0.36,
    acq_date: '2026-10-01',
    acq_time: '0852',
    satellite: 'Suomi-NPP',
    instrument: 'VIIRS',
    confidence: 'low',
    version: '2.0NRT',
    bright_t31: 291.5,
    frp: 12.5,
    daynight: 'N',
    source_type: 'urban',
    risk_score: 18.0,
    risk_level: 'low',
    is_anomaly: false,
    cluster_id: null,
    cluster_size: 1,
    nearest_place: 'Industrial District South, Seattle, WA',
    last_updated: '2026-10-01T09:00:00Z',
  },
  {
    id: 'VIIRS-NOAA20-20261001-010',
    latitude: 19.4215,
    longitude: -155.2871,
    brightness: 348.9,
    scan: 0.42,
    track: 0.39,
    acq_date: '2026-10-01',
    acq_time: '1005',
    satellite: 'NOAA-20',
    instrument: 'VIIRS',
    confidence: 'high',
    version: '2.0NRT',
    bright_t31: 297.6,
    frp: 165.0,
    daynight: 'N',
    source_type: 'volcanic',
    risk_score: 62.0,
    risk_level: 'high',
    is_anomaly: false,
    cluster_id: 'CL-KILAUEA',
    cluster_size: 1,
    nearest_place: "Halema'uma'u Crater, Hawaii Volcanoes National Park, HI",
    last_updated: '2026-10-01T10:15:00Z',
  },
];

export const mockIncidents: Record<string, IncidentDetail> = {
  'VIIRS-SNPP-20261001-001': {
    hotspot: mockHotspots[0],
    geospatial: {
      land_cover: 'Dense Coniferous Pine Forest',
      nearest_infrastructure: 'State Route 175 & PG&E 115kV Transmission Line',
      distance_to_infrastructure_meters: 450.0,
      nearest_settlement: 'Cobb Mountain Community & Geysers Resort',
      distance_to_settlement_meters: 1200.0,
      is_protected_area: true,
      protected_area_name: 'Boggs Mountain Demonstration State Forest',
      elevation_meters: 985.0,
      slope_degrees: 28.5,
      fuel_load_estimate: 'Extreme Dry Chaparral / Timber Litter (Fuel Model 10)',
    },
    weather: {
      temperature_celsius: 29.4,
      relative_humidity_percent: 14.0,
      wind_speed_kmh: 38.5,
      wind_gust_kmh: 58.0,
      wind_direction_degrees: 42.0,
      wind_direction_cardinal: 'NE',
      precipitation_mm: 0.0,
      fire_weather_index: 88.5,
      forecast_summary: 'Red Flag Warning in effect. Gusty offshore Diablo winds and critically dry fuels.',
    },
    historical: {
      prior_detections_30d: 1,
      prior_detections_90d: 3,
      is_recurrent_site: false,
      recurrent_pattern: 'none (novel wildland ignition)',
      first_detected_date: '2026-09-28',
      detection_frequency_score: 0.12,
    },
    intelligence: {
      hotspot_id: 'VIIRS-SNPP-20261001-001',
      classification: {
        predicted_source: 'wildfire',
        confidence: 0.96,
        probabilities: {
          wildfire: 0.96,
          prescribed_burn: 0.02,
          agricultural: 0.01,
          industrial: 0.005,
          urban: 0.003,
          volcanic: 0.002,
        },
        feature_importance: {
          fire_radiative_power: 0.38,
          wind_speed: 0.24,
          land_cover_fuel: 0.22,
          humidity: 0.16,
        },
      },
      anomaly: {
        is_anomaly: true,
        anomaly_score: 0.94,
        baseline_deviation: 4.8,
        anomaly_rationale: 'FRP of 142.8 MW is 4.8 sigma above historical 30-day baseline for this spatial grid cell.',
      },
      risk: {
        risk_score: 92.5,
        risk_level: 'critical',
        frp_component: 94.0,
        weather_component: 96.0,
        proximity_component: 88.0,
        historical_component: 20.0,
        explainable_factors: [
          {
            factor: 'Extreme Fire Radiative Power (142.8 MW)',
            weight: 0.35,
            impact: 'critical',
            description: 'Intense convective thermal energy indicative of rapidly advancing canopy crown fire.',
          },
          {
            factor: 'Critical Fire Weather (RH 14%, Winds 38.5 km/h)',
            weight: 0.30,
            impact: 'critical',
            description: 'Offshore wind gusts exceeding 58 km/h align with steep slope, creating extreme forward spotting potential.',
          },
          {
            factor: 'Settlement Proximity (< 1.5 km)',
            weight: 0.25,
            impact: 'critical',
            description: 'Under 1.2 km from Cobb residential fringe and power transmission corridor.',
          },
          {
            factor: 'Steep Terrain Slope (28.5°)',
            weight: 0.10,
            impact: 'high',
            description: 'Uphill terrain orientation amplifies convective preheating of downslope fuel beds.',
          },
        ],
        recommended_action: 'Issue immediate structural defense advisory and alert local CalFire dispatch unit Sonoma-Lake-Napa.',
      },
      model_version: 'v1.0-rf-heuristic',
      evaluated_at: '2026-10-01T08:52:00Z',
    },
    timeline: [
      {
        timestamp: '2026-10-01T08:45:00Z',
        event_type: 'satellite_pass',
        summary: 'Suomi-NPP VIIRS pass detected 142.8 MW thermal anomaly',
        details: {
          satellite: 'Suomi-NPP',
          brightness_k: 352.4,
          confidence: 'high',
        },
      },
      {
        timestamp: '2026-10-01T08:48:00Z',
        event_type: 'weather_shift',
        summary: 'Synoptic weather station reported wind gusts escalating to 58 km/h NE',
        details: {
          gust_kmh: 58.0,
          rh_percent: 14.0,
        },
      },
      {
        timestamp: '2026-10-01T08:50:00Z',
        event_type: 'alert_triggered',
        summary: 'Critical severity alert ALT-20261001-001 generated by ThermalIntel AI Engine',
        details: {
          composite_risk: 92.5,
          level: 'critical',
        },
      },
    ],
    data_mode: 'demo',
  },
  'VIIRS-SNPP-20261001-002': {
    hotspot: mockHotspots[1],
    geospatial: {
      land_cover: 'Chaparral & Mixed Montane Hardwood',
      nearest_infrastructure: 'Geothermal Steam Pipeline Trunk & Access Road',
      distance_to_infrastructure_meters: 280.0,
      nearest_settlement: 'Anderson Springs Settlement',
      distance_to_settlement_meters: 1850.0,
      is_protected_area: false,
      protected_area_name: null,
      elevation_meters: 1040.0,
      slope_degrees: 31.0,
      fuel_load_estimate: 'High Dry Brush (Fuel Model 4)',
    },
    weather: {
      temperature_celsius: 29.8,
      relative_humidity_percent: 13.5,
      wind_speed_kmh: 40.0,
      wind_gust_kmh: 62.0,
      wind_direction_degrees: 45.0,
      wind_direction_cardinal: 'NE',
      precipitation_mm: 0.0,
      fire_weather_index: 91.0,
      forecast_summary: 'Extreme fire behavior conditions. High spotting hazard.',
    },
    historical: {
      prior_detections_30d: 0,
      prior_detections_90d: 1,
      is_recurrent_site: false,
      recurrent_pattern: 'none',
      first_detected_date: '2026-10-01',
      detection_frequency_score: 0.05,
    },
    intelligence: {
      hotspot_id: 'VIIRS-SNPP-20261001-002',
      classification: {
        predicted_source: 'wildfire',
        confidence: 0.95,
        probabilities: { wildfire: 0.95, prescribed_burn: 0.03, industrial: 0.01, urban: 0.01 },
      },
      anomaly: {
        is_anomaly: true,
        anomaly_score: 0.91,
        baseline_deviation: 4.2,
        anomaly_rationale: 'Thermal radiative power exceeds 99th percentile for Northern California inland mountain ridge.',
      },
      risk: {
        risk_score: 89.0,
        risk_level: 'critical',
        frp_component: 91.0,
        weather_component: 95.0,
        proximity_component: 82.0,
        historical_component: 15.0,
        explainable_factors: [
          {
            factor: 'Severe Thermal Radiance (118.2 MW)',
            weight: 0.35,
            impact: 'critical',
            description: 'Rapid fuel consumption indicating active crown flame front.',
          },
          {
            factor: 'Diablo Wind Gusts (62 km/h NE)',
            weight: 0.30,
            impact: 'critical',
            description: 'High velocity down-canyon winds accelerating rate of spread toward Geysers infrastructure.',
          },
          {
            factor: 'Pipeline Proximity (280 m)',
            weight: 0.25,
            impact: 'high',
            description: 'Direct exposure risk to geothermal surface infrastructure and electrical transmission feeders.',
          },
        ],
        recommended_action: 'Coordinate aerial retardant drop along Geysers Ridge to prevent flanking spread.',
      },
      model_version: 'v1.0-rf-heuristic',
      evaluated_at: '2026-10-01T08:52:00Z',
    },
    timeline: [
      {
        timestamp: '2026-10-01T08:45:00Z',
        event_type: 'satellite_pass',
        summary: 'Suomi-NPP VIIRS pass detected 118.2 MW thermal radiance',
      },
    ],
    data_mode: 'demo',
  },
  'VIIRS-SNPP-20261001-004': {
    hotspot: mockHotspots[3],
    geospatial: {
      land_cover: 'Heavy Industrial / Refining Terminal',
      nearest_infrastructure: 'Houston Ship Channel Petrochemical Terminal Pier 4',
      distance_to_infrastructure_meters: 120.0,
      nearest_settlement: 'Pasadena Industrial Suburb',
      distance_to_settlement_meters: 3400.0,
      is_protected_area: false,
      protected_area_name: null,
      elevation_meters: 8.0,
      slope_degrees: 0.5,
      fuel_load_estimate: 'Non-vegetated (Concrete / Steel)',
    },
    weather: {
      temperature_celsius: 24.2,
      relative_humidity_percent: 68.0,
      wind_speed_kmh: 14.2,
      wind_gust_kmh: 20.0,
      wind_direction_degrees: 160.0,
      wind_direction_cardinal: 'SSE',
      precipitation_mm: 0.0,
      fire_weather_index: 12.0,
      forecast_summary: 'Partly cloudy, moderate coastal humidity.',
    },
    historical: {
      prior_detections_30d: 42,
      prior_detections_90d: 118,
      is_recurrent_site: true,
      recurrent_pattern: 'known_industrial_stack',
      first_detected_date: '2024-03-15',
      detection_frequency_score: 0.98,
    },
    intelligence: {
      hotspot_id: 'VIIRS-SNPP-20261001-004',
      classification: {
        predicted_source: 'industrial',
        confidence: 0.99,
        probabilities: {
          industrial: 0.99,
          urban: 0.007,
          wildfire: 0.001,
          agricultural: 0.001,
          prescribed_burn: 0.001,
          volcanic: 0.0,
        },
        feature_importance: {
          historical_recurrence: 0.55,
          land_cover_industrial: 0.30,
          frp_variance: 0.15,
        },
      },
      anomaly: {
        is_anomaly: false,
        anomaly_score: 0.11,
        baseline_deviation: 0.2,
        anomaly_rationale: 'Consistent operational flare emission profile matching historical facility baseline.',
      },
      risk: {
        risk_score: 26.5,
        risk_level: 'medium',
        frp_component: 22.0,
        weather_component: 15.0,
        proximity_component: 40.0,
        historical_component: 85.0,
        explainable_factors: [
          {
            factor: 'Known Permitted Flare Stack Site',
            weight: 0.45,
            impact: 'low',
            description: 'Over 100 historical satellite detections confirm routine refinery stack operation.',
          },
          {
            factor: 'Zero Vegetative Fuel Load',
            weight: 0.35,
            impact: 'low',
            description: 'Constructed concrete and steel pad prevents ground propagation.',
          },
          {
            factor: 'High Proximity to Chemical Facility Assets',
            weight: 0.20,
            impact: 'medium',
            description: 'Hotspot is located inside high-density hazardous materials processing zone.',
          },
        ],
        recommended_action: 'Log as routine industrial emission. No wildland or emergency response deployment required.',
      },
      model_version: 'v1.0-rf-heuristic',
      evaluated_at: '2026-10-01T07:46:00Z',
    },
    timeline: [
      {
        timestamp: '2026-10-01T07:30:00Z',
        event_type: 'satellite_pass',
        summary: 'Suomi-NPP VIIRS pass recorded standard industrial signature',
        details: { frp_mw: 24.3, confidence: 'nominal' },
      },
    ],
    data_mode: 'demo',
  },
  'VIIRS-SNPP-20261001-006': {
    hotspot: mockHotspots[5],
    geospatial: {
      land_cover: 'Steep Montane Chaparral & Oak Woodland',
      nearest_infrastructure: 'Angeles Crest Highway (SR-2) & High Voltage Pylons',
      distance_to_infrastructure_meters: 320.0,
      nearest_settlement: 'Altadena Foothill Communities',
      distance_to_settlement_meters: 2100.0,
      is_protected_area: true,
      protected_area_name: 'Angeles National Forest & San Gabriel Mountains National Monument',
      elevation_meters: 1120.0,
      slope_degrees: 34.0,
      fuel_load_estimate: 'Old-growth Chamise Chaparral (Heavy fuel buildup)',
    },
    weather: {
      temperature_celsius: 32.1,
      relative_humidity_percent: 18.0,
      wind_speed_kmh: 28.0,
      wind_gust_kmh: 46.0,
      wind_direction_degrees: 30.0,
      wind_direction_cardinal: 'NNE',
      precipitation_mm: 0.0,
      fire_weather_index: 76.0,
      forecast_summary: 'Santa Ana wind event developing. Low recovery overnight.',
    },
    historical: {
      prior_detections_30d: 0,
      prior_detections_90d: 0,
      is_recurrent_site: false,
      recurrent_pattern: 'none',
      first_detected_date: '2026-10-01',
      detection_frequency_score: 0.0,
    },
    intelligence: {
      hotspot_id: 'VIIRS-SNPP-20261001-006',
      classification: {
        predicted_source: 'wildfire',
        confidence: 0.94,
        probabilities: { wildfire: 0.94, prescribed_burn: 0.04, urban: 0.02 },
      },
      anomaly: {
        is_anomaly: true,
        anomaly_score: 0.88,
        baseline_deviation: 3.9,
        anomaly_rationale: 'Thermal radiance 76.5 MW in steep canyon fuel bed with zero prior 90-day detections.',
      },
      risk: {
        risk_score: 79.2,
        risk_level: 'critical',
        frp_component: 82.0,
        weather_component: 84.0,
        proximity_component: 75.0,
        historical_component: 10.0,
        explainable_factors: [
          {
            factor: 'Severe Canyon Topography & Slope (34.0°)',
            weight: 0.35,
            impact: 'critical',
            description: 'Steep chimney effect accelerating upslope thermal pre-heating and ember transport.',
          },
          {
            factor: 'Low Relative Humidity (18%) & Santa Ana Winds',
            weight: 0.30,
            impact: 'critical',
            description: 'Critically dry live fuel moisture below historical critical thresholds.',
          },
          {
            factor: 'Proximity to Angeles Crest Corridor & Power Grid',
            weight: 0.20,
            impact: 'high',
            description: '320 meters from primary highway transit route and transmission pylons.',
          },
          {
            factor: 'Protected National Forest Parkland',
            weight: 0.15,
            impact: 'high',
            description: 'High ecological sensitivity zone inside San Gabriel Mountains Monument.',
          },
        ],
        recommended_action: 'Deploy aerial reconnaissance to verify ignition perimeter and initiate trail evacuation protocols.',
      },
      model_version: 'v1.0-rf-heuristic',
      evaluated_at: '2026-10-01T08:56:00Z',
    },
    timeline: [
      {
        timestamp: '2026-10-01T08:48:00Z',
        event_type: 'satellite_pass',
        summary: 'Suomi-NPP pass identified 76.5 MW thermal anomaly in steep canyon',
      },
      {
        timestamp: '2026-10-01T08:55:00Z',
        event_type: 'alert_triggered',
        summary: 'Critical alert ALT-20261001-002 triggered for Angeles National Forest',
      },
    ],
    data_mode: 'demo',
  },
  'VIIRS-NOAA20-20261001-010': {
    hotspot: mockHotspots[9],
    geospatial: {
      land_cover: 'Barren Volcanic Basalt / Caldera Floor',
      nearest_infrastructure: 'Crater Rim Drive & USGS Volcano Observatory Sensor Network',
      distance_to_infrastructure_meters: 650.0,
      nearest_settlement: 'Volcano Village',
      distance_to_settlement_meters: 4800.0,
      is_protected_area: true,
      protected_area_name: 'Hawaii Volcanoes National Park',
      elevation_meters: 1222.0,
      slope_degrees: 8.0,
      fuel_load_estimate: 'Non-vegetated (Molten Lava / Basaltic Tephra)',
    },
    weather: {
      temperature_celsius: 19.5,
      relative_humidity_percent: 82.0,
      wind_speed_kmh: 22.0,
      wind_gust_kmh: 32.0,
      wind_direction_degrees: 75.0,
      wind_direction_cardinal: 'ENE',
      precipitation_mm: 1.2,
      fire_weather_index: 5.0,
      forecast_summary: 'Trade winds blowing vog (volcanic smog) southwest into Kaʻū district.',
    },
    historical: {
      prior_detections_30d: 85,
      prior_detections_90d: 260,
      is_recurrent_site: true,
      recurrent_pattern: 'semi-continuous_effusive_volcanism',
      first_detected_date: '2021-09-29',
      detection_frequency_score: 0.99,
    },
    intelligence: {
      hotspot_id: 'VIIRS-NOAA20-20261001-010',
      classification: {
        predicted_source: 'volcanic',
        confidence: 0.98,
        probabilities: { volcanic: 0.98, industrial: 0.01, wildfire: 0.01 },
      },
      anomaly: {
        is_anomaly: false,
        anomaly_score: 0.42,
        baseline_deviation: 1.2,
        anomaly_rationale: 'Elevated thermal radiance consistent with active lava lake fountain phase.',
      },
      risk: {
        risk_score: 62.0,
        risk_level: 'high',
        frp_component: 98.0,
        weather_component: 10.0,
        proximity_component: 35.0,
        historical_component: 95.0,
        explainable_factors: [
          {
            factor: 'Extreme Thermal Output (165.0 MW)',
            weight: 0.40,
            impact: 'critical',
            description: 'Massive radiant energy from exposed active basaltic lava lake.',
          },
          {
            factor: 'Volcanic Gas & Sulfur Plume Dispersion',
            weight: 0.35,
            impact: 'high',
            description: 'Elevated SO2 emissions impacting regional air quality in southwest communities.',
          },
          {
            factor: 'Zero Wildland Fuel Hazard',
            weight: 0.25,
            impact: 'low',
            description: 'Caldera lava lake is contained entirely within sheer pit crater basalt walls.',
          },
        ],
        recommended_action: 'Maintain aviation plume warning; monitor USGS HVO tiltmeter and gas sensor telemetry.',
      },
      model_version: 'v1.0-rf-heuristic',
      evaluated_at: '2026-10-01T10:16:00Z',
    },
    timeline: [
      {
        timestamp: '2026-10-01T10:05:00Z',
        event_type: 'satellite_pass',
        summary: 'NOAA-20 VIIRS recorded 165.0 MW thermal effusion in Halemaʻumaʻu',
      },
      {
        timestamp: '2026-10-01T10:15:00Z',
        event_type: 'alert_triggered',
        summary: 'Aviation vog advisory alert ALT-20261001-003 dispatched',
      },
    ],
    data_mode: 'demo',
  },
};

// Fill fallback for remaining hotspots so every hotspot click has an authentic deep-dive dossier!
mockHotspots.forEach((h) => {
  if (!mockIncidents[h.id]) {
    mockIncidents[h.id] = {
      hotspot: h,
      geospatial: {
        land_cover: h.source_type === 'agricultural' ? 'Cultivated Farmland & Orchards' : 'Forest and Shrubland',
        nearest_infrastructure: 'County Route & Regional Irrigation Canal',
        distance_to_infrastructure_meters: 420.0,
        nearest_settlement: h.nearest_place?.split(',')[0] || 'Local Rural District',
        distance_to_settlement_meters: 2800.0,
        is_protected_area: false,
        elevation_meters: 150.0,
        slope_degrees: 4.0,
        fuel_load_estimate: 'Crop Residue / Grass',
      },
      weather: {
        temperature_celsius: 26.5,
        relative_humidity_percent: 32.0,
        wind_speed_kmh: 18.0,
        wind_gust_kmh: 26.0,
        wind_direction_degrees: 310.0,
        wind_direction_cardinal: 'NW',
        precipitation_mm: 0.0,
        fire_weather_index: 38.0,
        forecast_summary: 'Typical seasonal conditions with light breeze.',
      },
      historical: {
        prior_detections_30d: 4,
        prior_detections_90d: 12,
        is_recurrent_site: false,
        detection_frequency_score: 0.25,
      },
      intelligence: {
        hotspot_id: h.id,
        classification: {
          predicted_source: h.source_type,
          confidence: h.confidence === 'high' ? 0.92 : 0.82,
          probabilities: { [h.source_type]: 0.88, unknown: 0.12 },
        },
        anomaly: {
          is_anomaly: h.is_anomaly,
          anomaly_score: h.is_anomaly ? 0.85 : 0.25,
          baseline_deviation: h.is_anomaly ? 3.4 : 0.6,
          anomaly_rationale: h.is_anomaly
            ? 'Thermal radiance surge above baseline for this coordinates quadrant.'
            : 'Thermal output aligns with expected seasonal parameters.',
        },
        risk: {
          risk_score: h.risk_score,
          risk_level: h.risk_level,
          frp_component: Math.min(100, h.frp),
          weather_component: 45.0,
          proximity_component: 40.0,
          historical_component: 30.0,
          explainable_factors: [
            {
              factor: `Radiative Power Level (${h.frp} MW)`,
              weight: 0.4,
              impact: h.risk_level,
              description: `Observed FRP of ${h.frp} MW aligns with ${h.source_type} classification expectations.`,
            },
            {
              factor: 'Atmospheric Environmental Moisture',
              weight: 0.3,
              impact: h.risk_level === 'critical' ? 'critical' : 'medium',
              description: 'Local wind and moisture conditions monitored via synoptic Open-Meteo grid.',
            },
            {
              factor: 'Geospatial Asset Proximity',
              weight: 0.3,
              impact: 'medium',
              description: `Located in vicinity of ${h.nearest_place}.`,
            },
          ],
          recommended_action:
            h.risk_level === 'critical' || h.risk_level === 'high'
              ? 'Dispatch local surveillance unit and verify status.'
              : 'Routine monitoring active; no emergency mobilization required.',
        },
        model_version: 'v1.0-rf-heuristic',
        evaluated_at: h.last_updated,
      },
      timeline: [
        {
          timestamp: `${h.acq_date}T${h.acq_time.slice(0, 2)}:${h.acq_time.slice(2, 4)}:00Z`,
          event_type: 'satellite_pass',
          summary: `${h.satellite} VIIRS pass detected ${h.frp} MW anomaly`,
          details: { brightness_k: h.brightness, confidence: h.confidence },
        },
      ],
      data_mode: 'demo',
    };
  }
});

export const mockAlerts: Alert[] = [
  {
    id: 'ALT-20261001-001',
    hotspot_id: 'VIIRS-SNPP-20261001-001',
    severity: 'critical',
    title: 'Rapid Convective Flare & Settlement Threat - Sonoma Basin',
    message:
      'FRP peaked at 142.8 MW within 1.2km of Cobb settlement. High wind gusts (58 km/h NE) creating extreme forward spotting hazard.',
    risk_score: 92.5,
    location_name: 'Geysers Basin, Sonoma County, CA',
    latitude: 38.7421,
    longitude: -122.8105,
    timestamp: '2026-10-01T08:50:00Z',
    is_acknowledged: false,
    recommended_action:
      'Trigger emergency zone alert; coordinate structural defense with CalFire Unit Sonoma-Lake-Napa.',
    tags: ['wildfire', 'high_wind', 'settlement_proximity', 'critical_frp'],
  },
  {
    id: 'ALT-20261001-002',
    hotspot_id: 'VIIRS-SNPP-20261001-006',
    severity: 'critical',
    title: 'Uncontained Canopy Fire - Angeles National Forest',
    message:
      'Thermal anomaly 76.5 MW detected in steep chaparral terrain with low humidity (18%). Potential rapid upslope chimney run toward transmission line.',
    risk_score: 79.2,
    location_name: 'Angeles National Forest Canyon, CA',
    latitude: 34.1852,
    longitude: -118.1528,
    timestamp: '2026-10-01T08:55:00Z',
    is_acknowledged: false,
    recommended_action:
      'Deploy aerial reconnaissance to verify ignition perimeter and initiate trail evacuation protocols.',
    tags: ['wildfire', 'forest_reserve', 'steep_slope', 'power_corridor'],
  },
  {
    id: 'ALT-20261001-003',
    hotspot_id: 'VIIRS-NOAA20-20261001-010',
    severity: 'warning',
    title: 'Elevated Effusive Thermal Surge - Halemaʻumaʻu',
    message:
      'High radiant power (165.0 MW) detected over volcanic caldera. No residential threat; aviation plume advisory active.',
    risk_score: 62.0,
    location_name: "Halema'uma'u Crater, Hawaii Volcanoes National Park, HI",
    latitude: 19.4215,
    longitude: -155.2871,
    timestamp: '2026-10-01T10:15:00Z',
    is_acknowledged: true,
    recommended_action:
      'Cross-reference USGS Hawaiian Volcano Observatory tiltmeter and sulfur dioxide telemetry.',
    tags: ['volcanic', 'plume_warning', 'remote_caldera'],
  },
];

export const mockSummary: SummaryResponse = {
  total_active_hotspots: 10,
  critical_risk_count: 4,
  high_risk_count: 2,
  medium_risk_count: 3,
  low_risk_count: 1,
  active_alerts_count: 3,
  average_frp: 67.06,
  max_frp: 165.0,
  average_risk_score: 62.4,
  data_mode: 'demo',
  last_sync_time: new Date().toISOString(),
  dominant_source: 'wildfire',
  source_counts: {
    wildfire: 4,
    industrial: 1,
    agricultural: 1,
    prescribed_burn: 1,
    urban: 1,
    volcanic: 1,
  },
  recent_critical_hotspots: mockHotspots.filter((h) => h.risk_level === 'critical'),
};

export const mockSources: SourcesResponse = {
  sources: [
    {
      source_type: 'wildfire',
      display_name: 'Wildfire / Forest Fire',
      count: 4,
      percentage: 40.0,
      average_frp: 97.9,
      average_risk: 84.2,
      primary_driver: 'Vegetative dry fuel & wind propagation',
    },
    {
      source_type: 'industrial',
      display_name: 'Industrial Facility / Flare Stack',
      count: 1,
      percentage: 10.0,
      average_frp: 24.3,
      average_risk: 26.5,
      primary_driver: 'Petrochemical, refining, & gas processing',
    },
    {
      source_type: 'agricultural',
      display_name: 'Agricultural Burn / Crop Clearing',
      count: 1,
      percentage: 10.0,
      average_frp: 31.8,
      average_risk: 38.0,
      primary_driver: 'Seasonal stubble burning & orchard maintenance',
    },
    {
      source_type: 'prescribed_burn',
      display_name: 'Prescribed Forest Management',
      count: 1,
      percentage: 10.0,
      average_frp: 44.0,
      average_risk: 35.0,
      primary_driver: 'Managed conservation fuel reduction treatment',
    },
    {
      source_type: 'urban',
      display_name: 'Urban / Structure Footprint',
      count: 1,
      percentage: 10.0,
      average_frp: 12.5,
      average_risk: 18.0,
      primary_driver: 'Commercial thermal mass & industrial district',
    },
    {
      source_type: 'volcanic',
      display_name: 'Volcanic Activity / Caldera',
      count: 1,
      percentage: 10.0,
      average_frp: 165.0,
      average_risk: 62.0,
      primary_driver: 'Basaltic effusive eruption & crater lava lake',
    },
  ],
  total_evaluated: 10,
  dominant_source: 'wildfire',
  data_mode: 'demo',
  generated_at: new Date().toISOString(),
};
